### ISSUE TITLE
Błąd w wyświetlaniu godziny w dzienniku

### ISSUE THREAD

**Issue by WewekYT** [Spythere/stacjownik#16]
Dziennik wyświetla przekreśloną godzinę rzeczywistą, a rozkładową pozostawia nietkniętą. Wydaje mi się, że powinno być na odwrót.

W przykładzie: 

1) Rozkład zakończony 13 minut przed czasem

2) Rozkład rozpoczęty 5 minut po czasie i zakończony minutę po.

![IMG_20220501_013708](https://user-images.githubusercontent.com/65121952/166126094-c90d718d-6f79-4139-ba09-c9c7130fffca.jpg)

**Comment by Spythere** [comment]
Dzięki, problem powinien być już rozwiązany. :)
